config/routes.rb
Rails.application.routes.draw do
  
  get 'facebook/sign_in' => 'facebook#sign_in'
  get 'facebook/sign_out' => 'facebook#sign_out'
  get 'inquiry' => 'profile#inquiry'
  get 'buy_credits' => 'profile#buy_credits'
  get 'about_us' => 'home#about_us'
  
  resources :home do 
    member do 
      get 'apply'
    end
  end

  resources :communities
  resources :agencies

  resources :profile do 
    member do 
      get 'applicants'
      get 'posts'
    end
  end

  namespace :api do 
    resources :users, only: [:create]  
  end

  root 'home#index'

end

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k}" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close' 
      span aria-hidden='true' &times;
    = v

app/views/shared/_header.html.slim
header.main-header
  / logo
  = link_to root_path, class: 'logo' do
    strong Connect Mo - OFW
  nav.navbar.navbar-static-top role='navigation'
    a.sidebar-toggle data-toggle='offcanvas' role='button'
      span.ion-navicon-round
      span.sr-only Toggle Navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        - if @current_user
          li.dropdown.user.user-menu
            a.dropdown-toggle data-toggle='dropdown'
              div
                = image_tag(@current_user['small_picture'], class: 'user-image' )
                span = @current_user['full_name']
            ul.dropdown-menu
              li.user-header
                = image_tag(@current_user['big_picture'], class: 'image-circle')
                p = @current_user['full_name']
                p from #{@current_user['current_location']}
              li.user-body
                .clearfix
                  .pull-left
                    strong Last sign in
                  .pull-right
                    p #{timeago_tag(sign_in_time, :nojs => true, :limit => 10.days.ago)}
                .clearfix
                  .pull-left
                    strong Birthday
                  .pull-right
                    p = @current_user['birthday']
                .clearfix
                  .pull-left
                    strong Gender
                  .pull-right
                    p = @current_user['gender']
                .clearfix
                  .pull-left
                    strong Email
                  .pull-right
                    p = @current_user['email']

          li
            = link_to facebook_sign_out_path, title: 'sign out' do 
              span.ion-log-out
        - else
          li
            = link_to @fb_url, class: 'fb-login' do 
              = image_tag('fb-button.png')

app/views/shared/_loader.html.slim
.loader
  .inner-loader
    p.spinner.ion-android-locate.rotate
    p Loading...

app/views/shared/_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    ul.sidebar-menu
      li.header Navigation
      li.treeview
        = link_to root_path
          span.ion.ion-ios-home
          span Home
      - unless @current_user.nil?
        li.treeview
          = link_to applicants_profile_path(@current_user.id)
            span.ion.ion-person-stalker
            span Applicants
        li.treeview
        	a href="/inquiry"
        		span.ion.ion-checkmark-circled
        		span Subscribers
        li.treeview
        	= link_to community_path(@current_user.id)
        		span.ion.ion-ios-chatboxes-outline
        		span Chat
        li.treeview
          = link_to new_home_path
            span.ion.ion-ios-plus-outline
            span Post New Ad
        li.treeview
        	a href="/buy_credits"
        		span.ion.ion-social-bitcoin
        		span Buy Credits
        li.treeview
          a href="/about_us"
            span.ion.ion-ios-information-outline
            span About Us