config/routes.rb
Rails.application.routes.draw do
  
  get 'facebook/sign_in' => 'facebook#sign_in'
  get 'facebook/sign_out' => 'facebook#sign_out'
  get 'inquiry' => 'profile#inquiry'
  get 'buy_credits' => 'profile#buy_credits'
  get 'about_us' => 'home#about_us'
  
  resources :home do 
    member do 
      get 'apply'
    end
  end

  resources :communities
  resources :agencies

  resources :profile do 
    member do 
      get 'applicants'
      get 'posts'
    end
  end

  namespace :api do 
    resources :users, only: [:create]  
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.recent
    gon.recent_posts = @recent_posts
  end

  def show
    @application_status = @current_user.application_status(params[:id])
    @post = Post.find(params[:id])
    gon.post_location = { latitude: @post.latitude, longitude: @post.longitude }
  end

  def create
  end

  def update
    if params[:submit_application] == '1'
      @current_user.user_post_statuses.create({ remarks: params[:remarks], status: 'applied', post_id: params[:id] })
      flash.now[:success] = 'Application Submitted.'
      post = Post.find params[:id]
      ::Chikka::Send_Api.deliver({message: "Hi! Thank you for applying this #{post.category} - #{post.title}", number: @current_user.contact})
      return redirect_to home_path(id: params[:id], active_tab: params[:active_tab]), turbolinks: true
    end
  end

  def new
    if params[:new_post].present?
      ::Chikka::Send_Api.deliver({message: 'Hi! New Post available.', number: '639066050188'})
      ::Chikka::Send_Api.deliver({message: 'Hi! New Post available.', number: '639267117480'})
      render json: {success: true}, status: :ok
    end
  end

  def apply
  end

  def about_us
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def active?(params, mode)
    'active' if params[:active_tab] == mode
  end
end

app/views/home/_modal.html.slim
.modal.fade.bs-example-modal-lg tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
          button.close data-dismiss="modal" aria-label="Close" type="button"
            span aria-hidden="true" &times;
          h4.modal-title id="myModalLabel" Apply for this #{@post.category.humanize}
      / form role="form" action=home_path method="put"
      = form_tag(home_path, method: 'put') do
        .modal-body  
          input type="hidden" name="submit_application" value="1"
          input type="hidden" name="active_tab" value=params[:active_tab]
          .form-group 
            label for="name"
            input.form-control type="text" name="name" readonly="readonly" value=@current_user.try(:full_name)
          .form-group
            label Message
            textarea.form-control rows="3" name="remarks" placeholder="Enter your message..."
          .form-group
            label for="file" Upload a File
            input.form-control type="file"

          // if the user has already applied
          .table-responsive
            table.table.table-hover
              tbody
                tr
                  th Status
                  th Date
                  th Description
                - @application_status.each do |status|
                  tr 
                    td
                      span.label.label-info = status.status.humanize
                    td #{timeago_tag(status.created_at, :nojs => true, :limit => 10.days.ago)}
                    td = status.remarks
                - unless @application_status.empty?
                  tr 
                    td
                      span.label.label-info Applied
                    td 04/05/2015
                    td Submitted Application File via Connect Mo
                  tr
                    td
                      span.label.label-warning Pending
                    td 04/06/2015
                    td The agency has yet to view this application
                  tr
                    td
                      span.label.label-success Accepted
                    td 04/07/2015
                    td The agency has viewed the application 
                  tr 
                    td
                      span.label.label-danger Missing Files
                    td 04/08/2015
                    td Message from the Agency : "Can you send your Diploma, NSO, and NBI?"
                  tr
                    td
                      spand.label.label-primary Interview
                    td 04/09/2015
                    td Come to the office 04/10/2015 at 8:00 AM
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button" Close
          button.btn.btn-primary Apply
              

app/views/home/about_us.html.slim
section.content-header
	h1 About Us

section.content
	.row
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-ios-albums-outline
					h3.box-title Company Profile
				.box-body
					dl.dl-horizontal
						dt Company Name
						dd Code Freeze
						dt Address
						dd Manila, Philippines
						dt Website
						dd www.codefreeze.com
						dt Contact No. 
						dd 1234567890
						dt Contact Person
						dd Erwin, Jossie, Bobby
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-android-checkmark-circle
					h3.box-title Company Mission
				.box-body
					blockquote
						p Connect Mo provides solutions and answers for OFWs in their everyday interactions that gives them ease of access, comfortability, flexibility, constantly, and directly communicating with different agencies and landowners around the world. Connect Mo gives real time, simple status updates and follow ups to be able to each inquiry both offline and online. 
						p
						p Do you have any problems? I - Connect Mo - na yan! 
	.row
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-navicon-round
					h3.box-title Subscribe with us?
				.box-body
					h6 Questions? Email us : subscription@connectmo.com
	.row	
		.col-md-6
			button.btn.btn-block.btn-warning.btn-lg Subscribe to this agency

app/views/home/apply.html.slim
section.content-header
	h1 Application 
section.content
	.row
		.col-md-6 
			.box.box-info
					.box-header
						i.ion.ion-clipboard
						h3.box-title Apply for this job post
					.box-body
						form role="form"
				          .form-group 
				            label for="name"
				            input.form-control type="text" id="name" value="Juan Dela Cruz"
				          .form-group
				            label Message
				            textarea.form-control rows="3" placeholder="Enter your message..."
				          .form-group
				            label for="file" Upload a File
				            input.form-control type="file"
				        / if the user has already applied
				        .table-responsive
				          table.table.table-hover
				            tbody
				              tr
				                th Status
				                th Date
				                th Description
				              tr 
				                td
				                  span.label.label-info Applied
				                td 04/05/2015
				                td Submitted Application File via Connect Mo
				              tr
				                td
				                  span.label.label-warning Pending
				                td 04/06/2015
				                td The agency has yet to view this application
				              tr
				                td
				                  span.label.label-success Accepted
				                td 04/07/2015
				                td The agency has viewed the application 
				              tr 
				                td
				                  span.label.label-danger Missing Files
				                td 04/08/2015
				                td Message from the Agency : "Can you send your Diploma, NSO, and NBI?"
				              tr
				                td
				                  spand.label.label-primary Interview
				                td 04/09/2015
				                td Come to the office 04/10/2015 at 8:00 AM
	.row
		.col-md-6 			
			button.btn.btn-block.btn-default.btn-lg Cancel
			button.btn.btn-block.btn-primary.btn-lg Apply        

app/views/home/index.html.slim
.content
  .row
		.col-md-8
			#map.map
		.col-md-4
			.box.box-primary
				.box-header.with-border
					h3.box-title Recent Post
					.box-tools.pull-right
						button.btn.btn-box-tool data-widget="collapse"
							i.ion.ion-minus-round
				.box-body
					ul.products-list.product-list-in-box
						- @recent_posts.each do |post|
							li.item
								.product-info
									a{ href="/home/#{post.id}?active_tab=public_transport_route"}
										= "#{post.title.humanize}"
										- cat = (post.job?) ? 'warning' : 'info'
										span.label.pull-right class="label-#{cat}"= post.category.humanize										
									.product-description= post.description

			.info-box

app/views/home/new.html.slim
section.content-header
	h1 Post New Ad

section.content.new-post-map
	.row
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-ios-list-outline
					h3.box-title Choose Category
				.box-body
					.form-group
						label.radio-inline
								input type='radio' 
								span.text Job Advertisement
						label.radio-inline
								input type='radio' 
								span.text House for Rent
						label.radio-inline
								input type='radio' 
								span.text New Events
	.row
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-edit
					h3.box-title Details
				.box-body
					form role="form"
			          .form-group 
			            label for="name" Name
			            input.form-control type="text" id="name" value="Juan Dela Cruz"
			          .form-group
			            label Description
			            textarea.form-control rows="3" placeholder="Enter your message..."
	.row
		.col-md-6
			.box.box-solid
				.box-header.with-border
					i.ion.ion-map
					h3.box-title Location
				.box-body
					#map
	.row
		.col-md-6
				button.btn.btn-block.btn-success.btn-lg#post Post this advertisement
				button.btn.btn-block.btn-warning.btn-lg#post-and-blast Post and Blast this advertisement

app/views/home/show.html.slim
.slide-in
	- unless @post.blank?
		section.content-header
			h1 
				= @post.title
				label style="margin-left: 5px;"
					- if @post.job?
						sup
							small.label.label-danger =@post.category.humanize
					- elsif @post.rent?
						sup
							small.label.label-warning =@post.category.humanize

		section.content
			.row
				- if @post.job?
					.col-md-3.col-sm-6.col-xs-12
						.info-box
							span.info-box-icon.bg-red
								i.ion.ion-ios-people-outline
							.info-box-content
								span.info-box-text  
								span.info-box-text Employees Needed
								span.info-box-number 100

					.col-md-3.col-sm-6.col-xs-12
						.info-box
							span.info-box-icon.bg-aqua
								i.ion.ion-ios-people
							.info-box-content
								span.info-box-text  
								span.info-box-text Slots Available
								span.info-box-number 25
				- elsif @post.rent?
					.col-md-3.col-sm-6.col-xs-12
						.info-box
							span.info-box-icon.bg-red
								i.ion.ion-home
							.info-box-content
								span.info-box-text  
								span.info-box-text Address
								span.info-box-number = @post.address
					.col-md-3.col-sm-6.col-xs-12
						.info-box
							span.info-box-icon.bg-aqua
								i.ion.ion-social-usd-outline
							.info-box-content
								span.info-box-text  
								span.info-box-text Price
								span.info-box-number = @post.price
				/ Ratings
				.col-md-3.col-sm-6.col-xs-12
					.info-box
						span.info-box-icon.bg-yellow
							i.ion.ion-ios-star-outline
						.info-box-content
							span.info-box-text 
							span.info-box-text Ratings
							i.ion.ion-android-star
							i.ion.ion-android-star
							i.ion.ion-android-star
							i.ion.ion-android-star-half
							i.ion.ion-android-star-outline
							span.info-box-text Your Ratings go here
							i.ion.ion-android-star-outline
							i.ion.ion-android-star-outline
							i.ion.ion-android-star-outline
							i.ion.ion-android-star-outline
							i.ion.ion-android-star-outline
				.col-md-3.col-sm-6.col-xs-12
					- if @application_status.empty?
						// if the user has not applied yet
						button.btn.btn-block.btn-primary.btn-lg data-toggle="modal" data-target=".bs-example-modal-lg"	Apply Now
					- else
						// if the user has already applied
						button.btn.btn-block.btn-warning.btn-lg data-toggle="modal" data-target=".bs-example-modal-lg"	View Application

			.row
				/ map
				.col-md-8
					.nav-tabs-custom#map-tabs
						ul.nav.nav-tabs
							li class=active?(params, 'public_transport_route')
							  a href='#' data-tab='public_transport_route' data-toggle='tab' area-expanded='true'
							    span.ion.ion-android-bus
							    span Public Transport Route
							li class=active?(params, 'driving_route')
							  a href='#' data-tab='driving_route' data-toggle='tab' area-expanded='true'
							    span.ion.ion-android-car
							    span Driving Route
							li class=active?(params, 'pedestrian_route')
							  a href='#' data-tab='pedestrian_route' data-toggle='tab' area-expanded='true'
							    span.ion.ion-android-walk
							    span Pedestrian Route
						.tab-content.post-maps
						  .tab-pane#public_transport_route class=active?(params, 'public_transport_route')
						    .map-view#map_with_public_transport_route
						  .tab-pane#driving_route class=active?(params, 'driving_route')
						    .map-view#map_with_driving_route
						  .tab-pane#pedestrian_route class=active?(params, 'pedestrian_route')
						    .map-view#map_with_pedestrian_route

				
				.col-md-4
					/ agency
					.box.box-default
						.box-header.with-border
							i.ion.ion-ios-briefcase-outline
							h3.box-title Agency
							.box-tools.pull-right
								button.btn.btn-box-tool data-widget="collapse"
									i.ion.ion-minus-round
						.box-body
							= link_to agency_path(@post.user.id) do 
								h4 = @post.user.full_name
					/ description
					.box.box-default
						.box-header.with-border
							i.ion.ion-document-text
							h3.box-title Description
							.box-tools.pull-right
								button.btn.btn-box-tool data-widget="collapse"
									i.ion.ion-minus-round
						.box-body
							h6 = @post.description
					/ community
					.box.box-primary
						.box-header.with-border
							i.ion.ion-flag
							h3.box-title Community
							.box-tools.pull-right
								button.btn.btn-box-tool data-widget="collapse"
									i.ion.ion-minus-round
						.box-body.no-padding
							ul.nav.nav-pills.nav-stacked
								- if @post.user.communities.blank?
									li 
										p.text-center No Community Available
								- else 
									- @post.user.communities.each do |community|
										li 
											= link_to community_path(community.id) do
												= community.name
									
						.box-footer.text-center
							a.uppercase href="#" View all Community

					/ related post
					.box.box-info
						.box-header.with-border
							i.ion.ion-ios-compose-outline
							h3.box-title Related Post
							.box-tools.pull-right
								button.btn.btn-box-tool data-widget="collapse"
									i.ion.ion-minus-round
						.box-body
							ul.products-list.product-list-in-box
								- if @post.related_post.blank?
									p.text-center No Post Related Found.
								- else
									- @post.related_post.each do |p|
										li.item
											.product-img
												- if p.job?
													h4.ion.ion-briefcase style="margin: 0px; font-size: 28px;"
												- elsif p.rent?
													h4.ion.ion-home style="margin: 0px; font-size: 28px;"
											.product-info 
												= link_to home_path(p.id, active_tab: 'public_transport_route'), class: 'product-title' do
													span.product-description	
														= p.title
								
						.box-footer.text-center
							a.uppercase href="#" View all Related Posts
			
			- unless @post.requirements.blank?
				.row
					.col-md-8
						.box.box-warning
							.box-header.with-border
								h3.box-title Requirements
								.box-tools.pull-right
									button.btn.btn-box-tool data-widget="collapse"
										i.ion.ion-minus-round
							.box-body
								p = @post.requirements

			/ Comments
			.row
				.col-md-8
					.box.box-danger
						.box-header.with-border
							i.ion.ion-edit
							h3.box-title Comments
							.box-tools.pull-right
								button.btn.btn-box-tool data-widget="collapse"
									i.ion.ion-minus-round
						.box-body
							ul.products-list.product-list-in-box
								- if @post.comments.empty?
									li.item
										p.text-center No Comments Found.
								- else
									- @post.comments.each do |comment|
										li.item
											.product-img
												= image_tag(comment.user.small_picture, alt: 'User Image')
											.pull-right
												p #{timeago_tag(comment.created_at, :nojs => true, :limit => 10.days.ago)}
											.product-info 
												p.product-description = comment.message
								
						.box-footer.text-center
							a.uppercase href="#" View all Comments

	= render 'modal'



	      